// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieManagement.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Movie", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Actors")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)");

                b.Property<int>("CreatedById")
                    .HasColumnType("integer");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Director")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<DateTime>("FromDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("ImagePath")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("ProductionCompany")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<DateTime>("ReleaseDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("RunningTime")
                    .HasColumnType("integer");

                b.Property<bool>("Status")
                    .HasColumnType("boolean");

                b.Property<DateTime>("ToDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Trailer")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("Version")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("Movies");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Actors = "Sam Worthington, Zoe Saldana, Sigourney Weaver",
                        Content = "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora.",
                        CreatedById = 1,
                        CreatedDate = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                        Director = "James Cameron",
                        FromDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        ImagePath = "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
                        Name = "Avatar: The Way of Water",
                        ProductionCompany = "20th Century Studios",
                        ReleaseDate = new DateTime(2022, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                        RunningTime = 192,
                        Status = true,
                        ToDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        Trailer = "https://www.youtube.com/watch?v=d9MyW72ELq0",
                        Type = "Sci-Fi, Adventure",
                        Version = "3D IMAX"
                    },
                    new
                    {
                        Id = 2,
                        Actors = "Tom Cruise, Miles Teller, Jennifer Connelly",
                        Content = "After thirty years, Maverick is still pushing the envelope as a top naval aviator.",
                        CreatedById = 1,
                        CreatedDate = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                        Director = "Joseph Kosinski",
                        FromDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        ImagePath = "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
                        Name = "Top Gun: Maverick",
                        ProductionCompany = "Paramount Pictures",
                        ReleaseDate = new DateTime(2022, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                        RunningTime = 131,
                        Status = true,
                        ToDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        Trailer = "https://www.youtube.com/watch?v=qSqVVswa420",
                        Type = "Action, Drama",
                        Version = "2D, 4DX"
                    },
                    new
                    {
                        Id = 3,
                        Actors = "Tom Holland, Zendaya, Benedict Cumberbatch",
                        Content = "Spider-Man seeks help from Doctor Strange when his secret identity is revealed.",
                        CreatedById = 1,
                        CreatedDate = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                        Director = "Jon Watts",
                        FromDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        ImagePath = "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
                        Name = "Spider-Man: No Way Home",
                        ProductionCompany = "Sony Pictures",
                        ReleaseDate = new DateTime(2021, 12, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                        RunningTime = 148,
                        Status = true,
                        ToDate = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        Trailer = "https://www.youtube.com/watch?v=JfVOs4VSpmA",
                        Type = "Action, Adventure, Sci-Fi",
                        Version = "2D, 3D"
                    },
                    new
                    {
                        Id = 4,
                        Actors = "Angela Bassett, Letitia Wright, Lupita Nyong'o",
                        Content = "The people of Wakanda fight to protect their home from intervening world powers.",
                        CreatedById = 1,
                        CreatedDate = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                        Director = "Ryan Coogler",
                        FromDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        ImagePath = "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
                        Name = "Black Panther: Wakanda Forever",
                        ProductionCompany = "Marvel Studios",
                        ReleaseDate = new DateTime(2022, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                        RunningTime = 161,
                        Status = true,
                        ToDate = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        Trailer = "https://www.youtube.com/watch?v=_Z3QKkl1WyM",
                        Type = "Action, Adventure, Drama",
                        Version = "2D, IMAX"
                    },
                    new
                    {
                        Id = 5,
                        Actors = "Robert Pattinson, Zoë Kravitz, Paul Dano",
                        Content = "Batman ventures into Gotham City's underworld when a sadistic killer leaves behind a trail of cryptic clues.",
                        CreatedById = 1,
                        CreatedDate = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                        Director = "Matt Reeves",
                        FromDate = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                        ImagePath = "https://image.tmdb.org/t/p/w500/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
                        Name = "The Batman",
                        ProductionCompany = "Warner Bros.",
                        ReleaseDate = new DateTime(2022, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                        RunningTime = 176,
                        Status = true,
                        ToDate = new DateTime(2022, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                        Trailer = "https://www.youtube.com/watch?v=mqqft2x_Aa4",
                        Type = "Action, Crime, Drama",
                        Version = "2D, IMAX"
                    },
                    new
                    {
                        Id = 6,
                        Actors = "Timothée Chalamet, Rebecca Ferguson, Oscar Isaac",
                        Content = "Paul Atreides leads nomadic tribes in a war against the enemies of his family.",
                        CreatedById = 1,
                        CreatedDate = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                        Director = "Denis Villeneuve",
                        FromDate = new DateTime(2021, 10, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                        ImagePath = "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
                        Name = "Dune",
                        ProductionCompany = "Warner Bros.",
                        ReleaseDate = new DateTime(2021, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                        RunningTime = 155,
                        Status = true,
                        ToDate = new DateTime(2022, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                        Trailer = "https://www.youtube.com/watch?v=8g18jFHCLXk",
                        Type = "Sci-Fi, Adventure",
                        Version = "2D, IMAX"
                    },
                    new
                    {
                        Id = 7,
                        Actors = "Vin Diesel, Michelle Rodriguez, Jason Momoa",
                        Content = "Dom Toretto and his family are targeted by the vengeful son of drug kingpin Hernan Reyes.",
                        CreatedById = 1,
                        CreatedDate = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                        Director = "Louis Leterrier",
                        FromDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                        ImagePath = "https://image.tmdb.org/t/p/w500/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
                        Name = "Fast X",
                        ProductionCompany = "Universal Pictures",
                        ReleaseDate = new DateTime(2023, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                        RunningTime = 141,
                        Status = true,
                        ToDate = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                        Trailer = "https://www.youtube.com/watch?v=32RAq6JzY-w",
                        Type = "Action, Adventure, Crime",
                        Version = "2D, 4DX"
                    },
                    new
                    {
                        Id = 8,
                        Actors = "Cillian Murphy, Emily Blunt, Matt Damon",
                        Content = "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
                        CreatedById = 1,
                        CreatedDate = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                        Director = "Christopher Nolan",
                        FromDate = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                        ImagePath = "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
                        Name = "Oppenheimer",
                        ProductionCompany = "Universal Pictures",
                        ReleaseDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                        RunningTime = 180,
                        Status = true,
                        ToDate = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                        Trailer = "https://www.youtube.com/watch?v=uYPbbksJxIg",
                        Type = "Biography, Drama, History",
                        Version = "70mm IMAX"
                    },
                    new
                    {
                        Id = 9,
                        Actors = "Margot Robbie, Ryan Gosling, America Ferrera",
                        Content = "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land.",
                        CreatedById = 1,
                        CreatedDate = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                        Director = "Greta Gerwig",
                        FromDate = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                        ImagePath = "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
                        Name = "Barbie",
                        ProductionCompany = "Warner Bros.",
                        ReleaseDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                        RunningTime = 114,
                        Status = true,
                        ToDate = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                        Trailer = "https://www.youtube.com/watch?v=pBk4NYhWNMM",
                        Type = "Comedy, Adventure, Fantasy",
                        Version = "2D, Pink Format"
                    },
                    new
                    {
                        Id = 10,
                        Actors = "Keanu Reeves, Donnie Yen, Bill Skarsgård",
                        Content = "John Wick uncovers a path to defeating The High Table, but he must face a new enemy.",
                        CreatedById = 1,
                        CreatedDate = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                        Director = "Chad Stahelski",
                        FromDate = new DateTime(2023, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                        ImagePath = "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
                        Name = "John Wick: Chapter 4",
                        ProductionCompany = "Lionsgate",
                        ReleaseDate = new DateTime(2023, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                        RunningTime = 169,
                        Status = true,
                        ToDate = new DateTime(2023, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                        Trailer = "https://www.youtube.com/watch?v=qEVUtrk8_B4",
                        Type = "Action, Crime, Thriller",
                        Version = "2D, 4DX"
                    });
            });
#pragma warning restore 612, 618
        }
    }
}
